/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import com.example.service.Register;

public class App {

    public static void main(String[] args) {

        System.out.println("spring-configuration app is starting...");

        //  TODO-05: Instantiate the ApplicationContext using AnnotationConfigApplicationContext.
        ApplicationContext appContext = new AnnotationConfigApplicationContext(Config.class);

        //  TODO-06: Get the Register bean from the ApplicationContext.
        //  Lookup the bean by its name or type - your choice.
        Register register = appContext.getBean(Register.class);

        //  TODO-07: Call the computeTotal method on the Register bean.
        //  Pass in a double value of 100.00.
        //  Print the result to the console.
        double total = register.computeTotal(100.00);
        System.out.println("Total: " + total);

    }

    //  TODO-08: Organize your imports.  Save your work.
    //  Run this application.  It should print "Total: 105.0" to the console.
}
