/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.service;

import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import com.example.Config;

class RegisterTest {

    private static Register register;

    //  DONE-01:  Run this test.  It should pass.  
    //  This test class and the current configuration represents the solution from the previous lab.
    //  In the next step, you will change the configuration from Java configuration to Annotation-based configuration.
    
    @BeforeAll
    static void setup() {
        System.clearProperty("spring.profiles.active");
        ApplicationContext spring = 
            new AnnotationConfigApplicationContext(Config.class);
        register = spring.getBean(Register.class);        
    }

    @Test 
    void testRegister() {
        double result = register.computeTotal(100);
        Assertions.assertThat(result).isEqualTo(100.00 + 6.00);
        System.out.println(String.format("The computed total including tax is: %.2f", result));
    }

    //  DONE-07:  After you have completed the previous steps, run this test.  It should pass.
}
