/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.service;

import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import com.example.Config;


class RegisterCompoundTest {

    private static Register register;

    
    @BeforeAll
    static void setup() {

        //  DONE-11: (OPTIONAL) Use the System.setProperty method to set the 
        //  "spring.profiles.active" property to "compound" before instantiating the Spring ApplicationContext.
        //  Add a matching @Profile("compound") annotation to the CompoundSalesTaxCalculator class.
        //  Organize all imports, save all work.
    	System.setProperty("spring.profiles.active", "compound");

        ApplicationContext spring = 
            new AnnotationConfigApplicationContext(Config.class);
        register = spring.getBean(Register.class);        
    }

    //  DONE-12: (OPTIONAL)  Remove the @Disabled annotation from the method below.
    //  Run the test.  We still encounter a FAILURE.
    //  There is still something missing.  Examine the test result's stack trace and
    //  try to guess what the problem is before looking at the next step.
    @Test 
    void testRegister() {
        double result = register.computeTotal(100);
        Assertions.assertThat(result).isEqualTo(100.00 + 8.50);
        System.out.println(String.format("The computed total including tax is: %.2f", result));
    }

}
